version:                   '3.1'

services:
 node-mysql:
   container_name:         react-express-mysql
   image:                  mysql
   command:                --default-authentication-plugin=mysql_native_password
   restart:                always
   ports:
     - 3389:3306
   expose:
     - 3306
   environment:
     MYSQL_HOST:           localhost
     MYSQL_ROOT_PASSWORD:  Node@2020
     MYSQL_DATABASE:       node-db
     MYSQL_USER:           nodeAdmin
     MYSQL_PASSWORD:       Node@2020
   networks:
     - app-network

 web-app:
    depends_on:
     - node-mysql
    container_name:        react-express-web-app
    build:
        context:           ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    command:               "npm start"
    stdin_open:            true
    networks:
      - app-network

 api-app:
    depends_on:
     - web-app
    container_name:        react-express-web-api
    build:
        context:           ./api
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
    command:               "npm run dev"
    networks:
      - app-network

 phpmyadmin:
    image:                 phpmyadmin
    container_name:        phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart:               always
    ports:
     - 8080:80
    volumes:
      - /sessions
    networks:
      - app-network

networks:
  app-network:
    driver:                bridge